const fs = require('fs');
const path = require('path');

const original = fs.readFileSync('index.html', 'utf8');
const lines = original.split('\n');

// 1. New Head Block
const newHeadLines = [
  '  <meta charset="UTF-8" />',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />',
  '  <title data-i18n="page_title">Three Brothers Bayan Kuaförü | Manavgat Sarı Saç & Butik Tasarım</title>',
  '  <meta name="description" content="2014\'ten beri Manavgat\'ta Three Brothers olarak sarı saçta doğallık ve ustalık, kişiye özel renk analizi ve saç sağlığı odaklı butik kuaför deneyimi." />',
  '  <meta name="keywords" content="Manavgat bayan kuaförü, Manavgat kuaför, Manavgat sarı saç uzmanı, Manavgat balyaj, Manavgat ombre, Manavgat sombre, Manavgat mikro kaynak, Antalya kadın kuaförü, Three Brothers kuaför, Manavgat saç renklendirme" />',
  '  <meta name="author" content="Three Brothers Bayan Kuaförü" />',
  '  <meta name="robots" content="index, follow" />',
  '  <meta name="theme-color" content="#FAF7F2" />',
  '',
  '  <!-- Canonical -->',
  '  <link rel="canonical" href="https://threebrotherskuafor.com/" />',
  '',
  '  <!-- Geo Meta Tags for Local SEO (Manavgat, Antalya) -->',
  '  <meta name="geo.region" content="TR-07" />',
  '  <meta name="geo.placename" content="Manavgat, Antalya" />',
  '  <meta name="geo.position" content="36.7865;31.4428" />',
  '  <meta name="ICBM" content="36.7865, 31.4428" />',
  '',
  '  <!-- Open Graph / Facebook -->',
  '  <meta property="og:type" content="business.business" />',
  '  <meta property="og:title" content="Three Brothers Bayan Kuaförü | Manavgat Sarı Saç & Butik Tasarım" />',
  '  <meta property="og:description" content="2014\'ten beri Manavgat\'ta sarı saçta doğallık ve ustalık, kişiye özel renk analizi ve saç sağlığı odaklı butik kuaför deneyimi." />',
  '  <meta property="og:image" content="./images/hero-model.webp" />',
  '  <meta property="og:url" content="https://threebrotherskuafor.com/" />',
  '  <meta property="og:site_name" content="Three Brothers Bayan Kuaförü" />',
  '  <meta property="og:locale" content="tr_TR" />',
  '',
  '  <!-- Twitter Card -->',
  '  <meta name="twitter:card" content="summary_large_image" />',
  '  <meta name="twitter:title" content="Three Brothers Bayan Kuaförü | Manavgat Sarı Saç & Butik Tasarım" />',
  '  <meta name="twitter:description" content="2014\'ten beri Manavgat\'ta sarı saçta doğallık ve ustalık, kişiye özel renk analizi ve saç sağlığı odaklı butik kuaför deneyimi." />',
  '  <meta name="twitter:image" content="./images/hero-model.webp" />',
  '',
  '  <!-- Favicon -->',
  '  <link rel="icon" type="image/webp" href="./images/logo.webp" />',
  '  <link rel="apple-touch-icon" href="./images/logo.jpg" />',
  '',
  '  <!-- Google Fonts: Montserrat & Plus Jakarta Sans -->',
  '  <link rel="preconnect" href="https://fonts.googleapis.com" />',
  '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />',
  '  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&family=Plus+Jakarta+Sans:ital,wght@0,500;0,600;0,700;0,800;1,700;1,800&display=swap" rel="stylesheet" />',
  '',
  '  <!-- Precompiled Stylesheet -->',
  '  <link rel="stylesheet" href="./css/style.css" />',
  '',
  '  <!-- Multi-Language Engine -->',
  '  <script src="./js/i18n.js"></script>',
  '',
  '  <!-- Schema.org JSON-LD Structured Data (HairSalon / LocalBusiness) -->',
  '  <script type="application/ld+json">',
  '  {',
  '    "@context": "https://schema.org",',
  '    "@type": "HairSalon",',
  '    "name": "Three Brothers Bayan Kuaförü",',
  '    "image": "./images/hero-model.webp",',
  '    "telephone": "+905526856907",',
  '    "url": "https://threebrotherskuafor.com",',
  '    "hasMap": "https://maps.google.com/?cid=16986332279537405342",',
  '    "priceRange": "₺₺",',
  '    "sameAs": [',
  '      "https://www.instagram.com/threebrotherrrs/"',
  '    ],',
  '    "address": {',
  '      "@type": "PostalAddress",',
  '      "streetAddress": "Bahçelievler Mahallesi, Demokrasi Bulvarı No: 8Z1",',
  '      "addressLocality": "Manavgat",',
  '      "addressRegion": "Antalya",',
  '      "postalCode": "07600",',
  '      "addressCountry": "TR"',
  '    },',
  '    "geo": {',
  '      "@type": "GeoCoordinates",',
  '      "latitude": "36.7865",',
  '      "longitude": "31.4428"',
  '    },',
  '    "aggregateRating": {',
  '      "@type": "AggregateRating",',
  '      "ratingValue": "5.0",',
  '      "reviewCount": "119",',
  '      "bestRating": "5"',
  '    },',
  '    "openingHoursSpecification": [',
  '      {',
  '        "@type": "OpeningHoursSpecification",',
  '        "dayOfWeek": ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],',
  '        "opens": "08:30",',
  '        "closes": "20:30"',
  '      }',
  '    ]',
  '  }',
  '  </script>'
];

// 2. New Header & Drawer Lines
const newHeaderLines = [
  '  <!-- ==========================================  ',
  '       1. STICKY GLASSMORPHISM LUXURY HEADER',
  '  =========================================== -->',
  '  <header class="luxury-header" id="boutiqueHeader">',
  '    ',
  '    <!-- Sol: Logo & Marka İsmi -->',
  '    <a href="#hero" class="brand-link" aria-label="Three Brothers Ana Sayfa">',
  '      <img src="./images/logo.webp" alt="Three Brothers Logo" class="brand-logo-img" width="44" height="44" />',
  '      <div style="display: flex; flex-direction: column;">',
  '        <span class="brand-title notranslate" translate="no" data-i18n="brand_name">Three Brothers</span>',
  '        <span class="brand-subtitle" data-i18n="brand_tagline">BAYAN KUAFÖRÜ &bull; MANAVGAT</span>',
  '      </div>',
  '    </a>',
  '',
  '    <!-- Orta: Masaüstü Gezinme Menüsü (Smooth Scroll) -->',
  '    <nav class="nav-menu-desktop" aria-label="Ana Gezinme">',
  '      <a href="#hizmetler" class="nav-link" data-i18n="nav_services">Hizmetlerimiz</a>',
  '      <a href="hakkimizda.html" class="nav-link" data-i18n="nav_story">Hakkımızda</a>',
  '      <a href="#surec" class="nav-link" data-i18n="nav_process">Süreç</a>',
  '      <a href="#galeri" class="nav-link" data-i18n="nav_gallery">Galeri</a>',
  '      <a href="#yorumlar" class="nav-link" data-i18n="nav_reviews">Yorumlar</a>',
  '      <a href="#sss" class="nav-link" data-i18n="nav_faq">SSS</a>',
  '      <a href="#iletisim" class="nav-link" data-i18n="nav_contact">İletişim</a>',
  '    </nav>',
  '',
  '    <!-- Sağ: Çok Dilli Seçici + Instagram + Randevu Al + Mobil Menü -->',
  '    <div class="header-right-actions">',
  '      ',
  '      <!-- Çok Dilli Dil Seçici -->',
  '      <div class="lang-switcher" aria-label="Dil Seçimi">',
  '        <button class="lang-btn active" data-lang="tr" type="button" aria-label="Türkçe">TR</button>',
  '        <button class="lang-btn" data-lang="en" type="button" aria-label="English">EN</button>',
  '        <button class="lang-btn" data-lang="de" type="button" aria-label="Deutsch">DE</button>',
  '        <button class="lang-btn" data-lang="ru" type="button" aria-label="Русский">RU</button>',
  '        <button class="lang-btn" data-lang="ar" type="button" aria-label="العربية">AR</button>',
  '      </div>',
  '',
  '      <!-- Instagram İkon Butonu (Masaüstü) -->',
  '      <a href="https://www.instagram.com/threebrotherrrs/" target="_blank" rel="noopener noreferrer" class="header-insta-btn" aria-label="Instagram">',
  '        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">',
  '          <rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect>',
  '          <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path>',
  '          <line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line>',
  '        </svg>',
  '      </a>',
  '',
  '      <!-- WhatsApp Randevu Butonu (Masaüstü) -->',
  '      <a href="https://wa.me/905526856907?text=Merhaba,%20Three%20Brothers%20salonunuzdan%20randevu%20almak%20istiyorum." target="_blank" rel="noopener noreferrer" class="btn-header-wa" data-i18n="nav_book">',
  '        <svg width="15" height="15" viewBox="0 0 24 24" fill="currentColor">',
  '          <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981z"/>',
  '        </svg>',
  '        <span>Randevu Al</span>',
  '      </a>',
  '',
  '      <!-- Mobil Menü Butonu (Hamburger) -->',
  '      <button id="openMobileMenuBtn" onclick="toggleMenu()" type="button" aria-label="Menüyü Aç" class="mobile-menu-btn">',
  '        <span>MENU</span>',
  '        <span style="display: inline-block; width: 16px; height: 1.5px; background-color: currentColor;"></span>',
  '      </button>',
  '',
  '    </div>',
  '',
  '  </header>',
  '',
  '  <!-- Menü Arka Plan Karartması (Backdrop) -->',
  '  <div id="menu-backdrop" class="menu-backdrop" onclick="toggleMenu()"></div>',
  '',
  '  <!-- Sağdan Açılan Lüks Menü Çekmecesi (Mobile Drawer) -->',
  '  <aside id="side-drawer" class="side-drawer" aria-label="Gezinme Menüsü">',
  '    <div class="drawer-header">',
  '      <div class="drawer-brand">',
  '        <h3 data-i18n="brand_name" class="notranslate" translate="no">Three Brothers</h3>',
  '        <span data-i18n="brand_tagline">BAYAN KUAFÖRÜ · MANAVGAT</span>',
  '      </div>',
  '      <button class="drawer-close-btn" onclick="toggleMenu()" aria-label="Menüyü Kapat">',
  '        ✕',
  '      </button>',
  '    </div>',
  '',
  '    <nav class="drawer-nav">',
  '      <!-- Ana Navigasyon Linkleri -->',
  '      <ul class="drawer-main-links">',
  '        <li><a href="#hero" onclick="toggleMenu()"><span data-i18n="nav_home">Ana Sayfa</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="hakkimizda.html"><span data-i18n="nav_story">Hakkımızda</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#hizmetler" onclick="toggleMenu()"><span data-i18n="nav_services">Hizmetlerimiz</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#surec" onclick="toggleMenu()"><span data-i18n="nav_process">Süreç</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#galeri" onclick="toggleMenu()"><span data-i18n="nav_gallery">Galeri</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#yorumlar" onclick="toggleMenu()"><span data-i18n="nav_reviews">Yorumlar</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#sss" onclick="toggleMenu()"><span data-i18n="nav_faq">SSS</span> <span class="arrow">&rarr;</span></a></li>',
  '        <li><a href="#iletisim" onclick="toggleMenu()"><span data-i18n="nav_contact">İletişim</span> <span class="arrow">&rarr;</span></a></li>',
  '      </ul>',
  '',
  '      <!-- Hizmetler Hap Butonları (Pill Buttons) -->',
  '      <div class="drawer-services-section">',
  '        <span class="drawer-section-tag" data-i18n="drawer_services_tag">ÖZEL HİZMETLERİMİZ</span>',
  '        <div class="drawer-pills-grid">',
  '          <a href="balyaj.html" class="drawer-pill" data-i18n="srv1_title">Profesyonel Balyaj</a>',
  '          <a href="blonde.html" class="drawer-pill" data-i18n="srv3_title">Blonde & Sarı Saç</a>',
  '          <a href="kaynak.html" class="drawer-pill" data-i18n="srv5_title">Mikro Kaynak</a>',
  '          <a href="ombre.html" class="drawer-pill" data-i18n="reels2_badge">Ombre & Sombre</a>',
  '          <a href="renklendirme.html" class="drawer-pill" data-i18n="srv2_title">Kişiye Özel Renklendirme</a>',
  '        </div>',
  '      </div>',
  '',
  '      <!-- Alt İletişim & Aksiyon Bilgisi -->',
  '      <div class="drawer-footer-info">',
  '        <div class="drawer-contact-line">+90 552 685 69 07</div>',
  '        <div class="drawer-hours-line" data-i18n="footer_hours">Salı – Pazar | 08:30 – 20:30 (Pazartesi Kapalı)</div>',
  '        ',
  '        <div class="drawer-action-btns">',
  '          <a href="tel:+905526856907" class="drawer-btn-outline" data-i18n="c_btn_call">Hemen Ara</a>',
  '          <a href="https://wa.me/905526856907?text=Merhaba,%20Three%20Brothers%20salonunuzdan%20randevu%20almak%20istiyorum." target="_blank" rel="noopener noreferrer" class="drawer-btn-outline" data-i18n="c_btn_wa">WhatsApp Randevu</a>',
  '          <a href="https://maps.google.com/?cid=16986332279537405342" target="_blank" rel="noopener noreferrer" class="drawer-btn-outline" data-i18n="c_btn_maps">Konum & Yol Tarifi</a>',
  '        </div>',
  '      </div>',
  '    </nav>',
  '  </aside>'
];

// 3. New FAQ Lines
const newFaqLines = [
  '  <!-- ==========================================  ',
  '       8. SIKÇA SORULAN SORULAR (FAQ ACCORDION)',
  '  =========================================== -->',
  '  <section id="sss" class="boutique-section section-faq">',
  '    <div class="section-container">',
  '',
  '      <div class="section-header-center reveal-on-scroll">',
  '        <span class="section-kicker" data-i18n="faq_kicker">MERAK EDİLENLER</span>',
  '        <h2 class="section-title" data-i18n="faq_title">Sıkça Sorulan Sorular</h2>',
  '        <p class="section-desc" data-i18n="faq_desc">',
  '          Three Brothers salonumuzdaki hizmetler, saç analizi ve randevu süreci hakkında en çok sorulan sorular.',
  '        </p>',
  '      </div>',
  '',
  '      <div class="faq-container-box reveal-stagger-parent">',
  '',
  '        <!-- Soru 1: Balyaj ve Sombre süresi -->',
  '        <div class="faq-item reveal-stagger-item">',
  '          <button class="faq-question-btn" type="button" aria-expanded="false">',
  '            <span data-i18n="faq1_q">Balyaj ve Sombre renklendirme işlemleri ne kadar sürer?</span>',
  '            <span class="faq-chevron">▼</span>',
  '          </button>',
  '          <div class="faq-answer-body">',
  '            <p class="faq-answer-text" data-i18n="faq1_a">',
  '              Saçınızın uzunluğuna, yoğunluğuna ve mevcut tonuna bağlı olarak işlem süresi ortalama 3 ile 5 saat arasında değişmektedir. Randevu öncesinde saç analizi yapılarak net süre paylaşılır.',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- Soru 2: Açma ve sarışınlıkta yıpranma -->',
  '        <div class="faq-item reveal-stagger-item">',
  '          <button class="faq-question-btn" type="button" aria-expanded="false">',
  '            <span data-i18n="faq2_q">Açma ve sarışınlık işlemlerinde saçım yıpranır mı?</span>',
  '            <span class="faq-chevron">▼</span>',
  '          </button>',
  '          <div class="faq-answer-body">',
  '            <p class="faq-answer-text" data-i18n="faq2_a">',
  '              Biyolojik saç sağlığı protokolümüz kapsamında, açma işlemlerinde bağ koruyucu ve onarıcı profesyonel ürünler kullanıyoruz. Saçınızın sağlığını riske atacak hiçbir agresif işlemi onayınız olmadan uygulamıyoruz.',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- Soru 3: Mikro kapsül kaynak süresi -->',
  '        <div class="faq-item reveal-stagger-item">',
  '          <button class="faq-question-btn" type="button" aria-expanded="false">',
  '            <span data-i18n="faq3_q">Mikro kapsül kaynak ne kadar süre kullanılabilir?</span>',
  '            <span class="faq-chevron">▼</span>',
  '          </button>',
  '          <div class="faq-answer-body">',
  '            <p class="faq-answer-text" data-i18n="faq3_a">',
  '              Doğru bakım ile mikro kapsül kaynaklarımız 2.5 - 4 ay boyunca konforla kullanılabilir. Süre sonunda saçınıza zarar vermeden çıkarılır ve yeniden takılabilir.',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- Soru 4: Saç yıkama tavsiyesi -->',
  '        <div class="faq-item reveal-stagger-item">',
  '          <button class="faq-question-btn" type="button" aria-expanded="false">',
  '            <span data-i18n="faq4_q">Randevuya gelmeden önce saçımı yıkamalı mıyım?</span>',
  '            <span class="faq-chevron">▼</span>',
  '          </button>',
  '          <div class="faq-answer-body">',
  '            <p class="faq-answer-text" data-i18n="faq4_a">',
  '              Özellikle açma ve renklendirme işlemlerinde saç derinizin doğal yağ tabakasının korunması önerilir. Bu nedenle randevu günü saçınızı yıkamadan gelmeniz tavsiye edilir.',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '        <!-- Soru 5: Saç analizi & ön görüşme -->',
  '        <div class="faq-item reveal-stagger-item">',
  '          <button class="faq-question-btn" type="button" aria-expanded="false">',
  '            <span data-i18n="faq5_q">İşlem öncesinde saç analizi ve ön görüşme yapıyor musunuz?</span>',
  '            <span class="faq-chevron">▼</span>',
  '          </button>',
  '          <div class="faq-answer-body">',
  '            <p class="faq-answer-text" data-i18n="faq5_a">',
  '              Evet. Misafirlerimizin saç yapısını, geçmiş boya/açma geçmişini ve saçın elastikiyetini analiz etmeden hiçbir ağır işleme başlamıyoruz. Saç sağlığını tehlikeye atacak bir durum varsa dürüstçe alternatif çözümler öneriyoruz.',
  '            </p>',
  '          </div>',
  '        </div>',
  '',
  '      </div>',
  '',
  '    </div>',
  '  </section>'
];

// 4. New Mobile Float Bar Lines
const newFloatBarLines = [
  '  <!-- ==========================================  ',
  '       11. MOBILE FLOATING ACTION BAR (DUAL ACTION)',
  '  =========================================== -->',
  '  <div class="mobile-float-bar" aria-label="Mobil Hızlı Eylem Çubuğu">',
  '    <a href="tel:+905526856907" class="mobile-float-btn mobile-call-btn" aria-label="Telefonla Hemen Arayın">',
  '      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">',
  '        <path d="M6.62 10.79a15.053 15.053 0 006.59 6.59l2.2-2.2a1 1 0 011.02-.24c1.12.37 2.33.57 3.57.57a1 1 0 011 1V20a1 1 0 01-1 1A17 17 0 013 4a1 1 0 011-1h3.5a1 1 0 011 1c0 1.25.2 2.45.57 3.57a1 1 0 01-.25 1.02l-2.2 2.2z"/>',
  '      </svg>',
  '      <span data-i18n="c_btn_call">Hemen Ara</span>',
  '    </a>',
  '    <a href="https://wa.me/905526856907?text=Merhaba,%20Three%20Brothers%20salonunuzdan%20randevu%20almak%20istiyorum." target="_blank" rel="noopener noreferrer" class="mobile-float-btn mobile-wa-btn" aria-label="WhatsApp ile Randevu Al">',
  '      <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor">',
  '        <path d="M.057 24l1.687-6.163c-1.041-1.804-1.588-3.849-1.587-5.946.003-6.556 5.338-11.891 11.893-11.891 3.181.001 6.167 1.24 8.413 3.488 2.245 2.248 3.481 5.236 3.48 8.414-.003 6.557-5.338 11.892-11.893 11.892-1.99-.001-3.951-.5-5.688-1.448l-6.305 1.654zm6.597-3.807c1.676.995 3.276 1.591 5.392 1.592 5.448 0 9.886-4.434 9.889-9.885.002-5.462-4.415-9.89-9.881-9.892-5.452 0-9.887 4.434-9.889 9.884-.001 2.225.651 3.891 1.746 5.634l-.999 3.648 3.742-.981z"/>',
  '      </svg>',
  '      <span data-i18n="floating_wa">WhatsApp Randevu</span>',
  '    </a>',
  '  </div>'
];

// 5. New Unified Script Lines
const newScriptLines = [
  '  <!-- ==========================================  ',
  '       12. ULTRA-FAST & RESILIENT JAVASCRIPT ENGINE',
  '  =========================================== -->',
  '  <script>',
  '    // Global Drawer Toggle',
  '    function toggleMenu() {',
  '      const drawer = document.getElementById(\'side-drawer\');',
  '      const backdrop = document.getElementById(\'menu-backdrop\');',
  '      if (drawer && backdrop) {',
  '        drawer.classList.toggle(\'active\');',
  '        backdrop.classList.toggle(\'active\');',
  '        document.body.classList.toggle(\'menu-open\');',
  '      }',
  '    }',
  '    window.toggleMenu = toggleMenu;',
  '',
  '    document.addEventListener(\'DOMContentLoaded\', () => {',
  '      // 1. High-Performance IntersectionObserver for Scroll Reveals',
  '      const observerOptions = {',
  '        threshold: 0.12,',
  '        rootMargin: \'0px 0px -40px 0px\'',
  '      };',
  '',
  '      const revealTargets = document.querySelectorAll(\'.reveal-on-scroll, .reveal-stagger-parent\');',
  '',
  '      if (\'IntersectionObserver\' in window) {',
  '        const revealObserver = new IntersectionObserver((entries) => {',
  '          entries.forEach(entry => {',
  '            if (entry.isIntersecting) {',
  '              entry.target.classList.add(\'is-revealed\');',
  '            } else {',
  '              entry.target.classList.remove(\'is-revealed\');',
  '            }',
  '          });',
  '        }, observerOptions);',
  '',
  '        revealTargets.forEach(el => revealObserver.observe(el));',
  '      } else {',
  '        revealTargets.forEach(el => el.classList.add(\'is-revealed\'));',
  '      }',
  '',
  '      // 2. Count-Up Metric Animation for 2014 and 100%',
  '      const metricCards = document.querySelectorAll(\'.trust-metric-card\');',
  '      if (\'IntersectionObserver\' in window && metricCards.length > 0) {',
  '        let metricsAnimated = false;',
  '        const metricsObserver = new IntersectionObserver((entries) => {',
  '          entries.forEach(entry => {',
  '            if (entry.isIntersecting && !metricsAnimated) {',
  '              metricsAnimated = true;',
  '              animateCountUp(\'2014\', 0, 2014, 1600);',
  '              animateCountUp(\'%100\', 0, 100, 1400, \'%\');',
  '            }',
  '          });',
  '        }, { threshold: 0.2 });',
  '',
  '        const trustSection = document.getElementById(\'neden-biz\');',
  '        if (trustSection) metricsObserver.observe(trustSection);',
  '      }',
  '',
  '      function animateCountUp(targetIdText, start, end, duration, prefix = \'\') {',
  '        const elements = document.querySelectorAll(\'.trust-card-top-val\');',
  '        elements.forEach(el => {',
  '          if (el.textContent.trim().includes(\'2014\') && end === 2014) {',
  '            runCounter(el, start, end, duration, \'\');',
  '          } else if (el.textContent.trim().includes(\'100\') && end === 100) {',
  '            runCounter(el, start, end, duration, \'%\');',
  '          }',
  '        });',
  '      }',
  '',
  '      function runCounter(el, start, end, duration, symbol) {',
  '        const startTime = performance.now();',
  '        function update(now) {',
  '          const progress = Math.min((now - startTime) / duration, 1);',
  '          const easeProgress = progress === 1 ? 1 : 1 - Math.pow(2, -10 * progress);',
  '          const currentVal = Math.floor(start + (end - start) * easeProgress);',
  '          el.textContent = symbol === \'%\' ? \'%\' + currentVal : currentVal;',
  '          if (progress < 1) {',
  '            requestAnimationFrame(update);',
  '          } else {',
  '            el.textContent = symbol === \'%\' ? \'%100\' : \'2014\';',
  '          }',
  '        }',
  '        requestAnimationFrame(update);',
  '      }',
  '',
  '      // 3. Cinematic Hero Background Parallax',
  '      const prefersReducedMotion = window.matchMedia(\'(prefers-reduced-motion: reduce)\').matches;',
  '      const heroBgLayer = document.querySelector(\'.hero-bg-layer\');',
  '',
  '      if (!prefersReducedMotion && heroBgLayer && window.innerWidth > 768) {',
  '        let lastScrollY = 0;',
  '        let ticking = false;',
  '',
  '        window.addEventListener(\'scroll\', () => {',
  '          lastScrollY = window.scrollY;',
  '          if (!ticking) {',
  '            window.requestAnimationFrame(() => {',
  '              if (lastScrollY < window.innerHeight * 1.2) {',
  '                const translateY = (lastScrollY * 0.14).toFixed(2);',
  '                heroBgLayer.style.transform = \'translate3d(0, \' + translateY + \'px, 0)\';',
  '              }',
  '              ticking = false;',
  '            });',
  '            ticking = true;',
  '          }',
  '        }, { passive: true });',
  '      }',
  '',
  '      // 4. Header Shrink on Scroll (Sticky Header)',
  '      const header = document.getElementById(\'boutiqueHeader\') || document.querySelector(\'.luxury-header\');',
  '      function updateHeader() {',
  '        if (!header) return;',
  '        if (window.scrollY > 20) {',
  '          header.classList.add(\'is-scrolled\');',
  '        } else {',
  '          header.classList.remove(\'is-scrolled\');',
  '        }',
  '      }',
  '      window.addEventListener(\'scroll\', updateHeader, { passive: true });',
  '      updateHeader();',
  '',
  '      // 5. Drawer Link Click Auto-Close',
  '      const drawerLinks = document.querySelectorAll(\'.side-drawer a\');',
  '      drawerLinks.forEach(link => {',
  '        link.addEventListener(\'click\', () => {',
  '          const drawer = document.getElementById(\'side-drawer\');',
  '          const backdrop = document.getElementById(\'menu-backdrop\');',
  '          if (drawer && drawer.classList.contains(\'active\')) {',
  '            drawer.classList.remove(\'active\');',
  '            if (backdrop) backdrop.classList.remove(\'active\');',
  '            document.body.classList.remove(\'menu-open\');',
  '          }',
  '        });',
  '      });',
  '',
  '      // 6. Reels Video Interaction (Continuous Autoplay + Tap to Pause/Resume + Sound Toggle)',
  '      const reelWrappers = document.querySelectorAll(\'[data-reel-wrapper]\');',
  '      reelWrappers.forEach(wrapper => {',
  '        const video = wrapper.querySelector(\'video\');',
  '        const soundBtn = wrapper.querySelector(\'[data-sound-btn]\');',
  '        const soundOff = soundBtn ? soundBtn.querySelector(\'.sound-off-icon\') : null;',
  '        const soundOn = soundBtn ? soundBtn.querySelector(\'.sound-on-icon\') : null;',
  '',
  '        if (!video) return;',
  '',
  '        video.muted = true;',
  '        video.playsInline = true;',
  '        video.setAttribute(\'playsinline\', \'\');',
  '        video.setAttribute(\'webkit-playsinline\', \'\');',
  '',
  '        const safePlay = () => {',
  '          video.play().then(() => {',
  '            wrapper.classList.add(\'is-playing\');',
  '          }).catch(() => {',
  '            video.currentTime = 0.001;',
  '          });',
  '        };',
  '',
  '        if (video.readyState >= 2) {',
  '          safePlay();',
  '        } else {',
  '          video.addEventListener(\'loadeddata\', safePlay, { once: true });',
  '          video.addEventListener(\'canplay\', safePlay, { once: true });',
  '        }',
  '',
  '        if (soundBtn) {',
  '          soundBtn.addEventListener(\'click\', (e) => {',
  '            e.preventDefault();',
  '            e.stopPropagation();',
  '            video.muted = !video.muted;',
  '            if (video.muted) {',
  '              soundBtn.classList.remove(\'is-unmuted\');',
  '              if (soundOff) { soundOff.style.display = \'block\'; soundOff.classList.remove(\'hidden\'); }',
  '              if (soundOn) { soundOn.style.display = \'none\'; soundOn.classList.add(\'hidden\'); }',
  '            } else {',
  '              soundBtn.classList.add(\'is-unmuted\');',
  '              if (soundOff) { soundOff.style.display = \'none\'; soundOff.classList.add(\'hidden\'); }',
  '              if (soundOn) { soundOn.style.display = \'block\'; soundOn.classList.remove(\'hidden\'); }',
  '              if (video.paused) {',
  '                video.play();',
  '                wrapper.classList.add(\'is-playing\');',
  '              }',
  '            }',
  '          });',
  '        }',
  '',
  '        wrapper.addEventListener(\'click\', (e) => {',
  '          if (e.target.closest(\'[data-sound-btn]\') || e.target.closest(\'.reel-view-profile-btn\') || e.target.closest(\'a\') || e.target.closest(\'button\')) {',
  '            return;',
  '          }',
  '          if (video.paused) {',
  '            video.play().then(() => {',
  '              wrapper.classList.add(\'is-playing\');',
  '            }).catch(() => {',
  '              video.muted = true;',
  '              video.play();',
  '              wrapper.classList.add(\'is-playing\');',
  '            });',
  '          } else {',
  '            video.pause();',
  '            wrapper.classList.remove(\'is-playing\');',
  '          }',
  '        });',
  '',
  '        video.addEventListener(\'play\', () => wrapper.classList.add(\'is-playing\'));',
  '        video.addEventListener(\'pause\', () => wrapper.classList.remove(\'is-playing\'));',
  '        video.addEventListener(\'ended\', () => wrapper.classList.remove(\'is-playing\'));',
  '      });',
  '',
  '      // 7. Interactive Likes',
  '      const likeBtns = document.querySelectorAll(\'[data-like-btn]\');',
  '      likeBtns.forEach(btn => {',
  '        btn.addEventListener(\'click\', function(e) {',
  '          e.preventDefault();',
  '          this.classList.toggle(\'liked\');',
  '        });',
  '      });',
  '',
  '      // 8. FAQ Accordion (Smooth Expand/Collapse & Rotate Chevron)',
  '      const faqItems = document.querySelectorAll(\'.faq-item\');',
  '      faqItems.forEach(item => {',
  '        const btn = item.querySelector(\'.faq-question-btn\');',
  '        if (!btn) return;',
  '        btn.addEventListener(\'click\', () => {',
  '          const isActive = item.classList.contains(\'active\');',
  '          faqItems.forEach(otherItem => {',
  '            otherItem.classList.remove(\'active\');',
  '            const otherBtn = otherItem.querySelector(\'.faq-question-btn\');',
  '            if (otherBtn) otherBtn.setAttribute(\'aria-expanded\', \'false\');',
  '          });',
  '',
  '          if (!isActive) {',
  '            item.classList.add(\'active\');',
  '            btn.setAttribute(\'aria-expanded\', \'true\');',
  '          }',
  '        });',
  '      });',
  '',
  '      // 9. Single-Review Carousel Controller',
  '      (function() {',
  '        const track = document.getElementById(\'singleReviewsTrack\');',
  '        const prevBtn = document.getElementById(\'reviewPrevBtn\');',
  '        const nextBtn = document.getElementById(\'reviewNextBtn\');',
  '        const dotsContainer = document.getElementById(\'reviewDotsContainer\');',
  '        if (!track || !dotsContainer) return;',
  '',
  '        const dots = dotsContainer.querySelectorAll(\'.review-dot\');',
  '        const cards = track.querySelectorAll(\'.single-review-card\');',
  '        const totalCards = cards.length;',
  '        let currentIndex = 0;',
  '        let autoPlayInterval = null;',
  '',
  '        function updateActiveCard(index) {',
  '          if (index < 0) index = totalCards - 1;',
  '          if (index >= totalCards) index = 0;',
  '          currentIndex = index;',
  '',
  '          cards.forEach((card, i) => {',
  '            if (i === currentIndex) {',
  '              card.classList.add(\'active\');',
  '            } else {',
  '              card.classList.remove(\'active\');',
  '            }',
  '          });',
  '',
  '          dots.forEach((dot, i) => {',
  '            if (i === currentIndex) dot.classList.add(\'active\');',
  '            else dot.classList.remove(\'active\');',
  '          });',
  '        }',
  '',
  '        if (prevBtn) {',
  '          prevBtn.addEventListener(\'click\', () => {',
  '            updateActiveCard(currentIndex - 1);',
  '            resetAutoPlay();',
  '          });',
  '        }',
  '',
  '        if (nextBtn) {',
  '          nextBtn.addEventListener(\'click\', () => {',
  '            updateActiveCard(currentIndex + 1);',
  '            resetAutoPlay();',
  '          });',
  '        }',
  '',
  '        dots.forEach((dot, i) => {',
  '          dot.addEventListener(\'click\', () => {',
  '            updateActiveCard(i);',
  '            resetAutoPlay();',
  '          });',
  '        });',
  '',
  '        function startAutoPlay() {',
  '          autoPlayInterval = setInterval(() => {',
  '            updateActiveCard(currentIndex + 1);',
  '          }, 6500);',
  '        }',
  '',
  '        function resetAutoPlay() {',
  '          clearInterval(autoPlayInterval);',
  '          startAutoPlay();',
  '        }',
  '',
  '        track.addEventListener(\'mouseenter\', () => clearInterval(autoPlayInterval));',
  '        track.addEventListener(\'mouseleave\', () => startAutoPlay());',
  '        track.addEventListener(\'touchstart\', () => clearInterval(autoPlayInterval), { passive: true });',
  '',
  '        startAutoPlay();',
  '      })();',
  '    });',
  '  </script>'
];

// Perform line replacements:
// 1. Head (lines index 3 to 66)
// lines[0] = <!DOCTYPE html>
// lines[1] = <html lang="tr">
// lines[2] = <head>
// lines[66] = </head>
let resultLines = [];
resultLines.push(...lines.slice(0, 3)); // 0..2 (<head>)
resultLines.push(...newHeadLines);
resultLines.push(lines[66]); // </head>
resultLines.push(...lines.slice(67, 73)); // 67..72 (<body>, <div class="ambient-mesh-1"></div>)

// Header & Drawer (lines 73 to 155)
resultLines.push(...newHeaderLines);

// Hero through Gallery (lines 156 to 1054)
// Let's find index where id="sss" begins
const sssIndex = lines.findIndex(l => l.includes('<section id="sss"'));
resultLines.push(...lines.slice(156, sssIndex));

// SSS Accordion
resultLines.push(...newFaqLines);

// Contact through Footer (from after old SSS to mobile-float-bar)
const sssEndIndex = lines.findIndex((l, idx) => idx > sssIndex && l.includes('</section>'));
const floatBarIndex = lines.findIndex(l => l.includes('<div class="mobile-float-bar">'));
resultLines.push(...lines.slice(sssEndIndex + 1, floatBarIndex));

// Mobile Float Bar
resultLines.push(...newFloatBarLines);

// Footer & Scripts (from after old mobile float bar)
// Old mobile float bar ends at lines[1303] = </div>
const floatBarEndIndex = lines.findIndex((l, idx) => idx > floatBarIndex && l.includes('</div>'));
// Old scripts started at line 1308
// Old scripts end before </body>
const bodyEndIndex = lines.findIndex(l => l.includes('</body>'));

resultLines.push('');
resultLines.push(...newScriptLines);
resultLines.push('');
resultLines.push(...lines.slice(bodyEndIndex));

let finalHtml = resultLines.join('\n');
finalHtml = finalHtml.replace(/@threebrotherss/g, '@threebrotherrrs');

fs.writeFileSync('index.html', finalHtml, 'utf8');
fs.writeFileSync('public/index.html', finalHtml, 'utf8');
console.log(`Success! New index.html has ${resultLines.length} lines.`);
